name:   'Amy Blog'
url:    'https://amylao.work'
author: 'Amy'

include:  ['_pages']

plugins: [jekyll-paginate]
paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

markdown: 'kramdown'
kramdown:
    input: GFM
    syntax_highlighter: rouge

timezone: 'Asia/Shanghai'

analytics:
    provider: google
    google:
        tracking_id: ''

enable_disqus: false

